services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql_db_worker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_worker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # API Service
  bebii_dash:
    container_name: bebii_dash
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./public:/app/public
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_PORT=${APP_PORT}
      - APP_BASE_URL=${APP_BASE_URL}
      - DATABASE_URL=${DOCKER_DB_URL}
    depends_on:
      - db
    command: >
      sh -c "
        npx prisma db push --schema=./prisma/schema.prisma &&
        npm run start:prod
      "

volumes:
  db_data:
